- name: Creating alertmanager user group
  group: name="{{groupId}}"
  become: true

- name: Creating alertmanager user
  user:
    name: "{{userId}}"
    group: "{{groupId}}"
    system: yes
    shell: "/sbin/nologin"
    comment: "{{userId}} nologin User"
    createhome: "no"
    state: present

- name: Download alertmanager
  unarchive:
    src: "https://github.com/prometheus/alertmanager/releases/download/v{{ version }}/alertmanager-{{ version }}.linux-amd64.tar.gz"
    dest: /tmp/
    remote_src: yes
    creates: "/tmp/alertmanager-{{ version }}.linux-amd64.tar.gz"

- name: Copy alertmanager executable to bin
  copy:
    src: "/tmp/alertmanager-{{ version }}.linux-amd64/alertmanager"
    dest: "/usr/local/bin/alertmanager"
    owner: "{{userId}}"
    group: "{{groupId}}"
    remote_src: yes
    mode: 0755

- name: Creates data directory
  file: 
    path: "/data/alertmanager/"
    state: directory
    owner: "{{userId}}"
    group: "{{groupId}}"
    mode: 0755

- name: Creates config directory
  file: 
    path: "/etc/alertmanager/"
    state: directory
    owner: "{{userId}}"
    group: "{{groupId}}"
    mode: 0755

- name: Copy config file
  copy:
    src: "{{ role_path }}/files/alertmanager.yml"
    dest: /etc/alertmanager/alertmanager.yml

- name: Replace alertmanager config with env
  replace:
    path: /etc/alertmanager/alertmanager.yml
    regexp: '{{ item.regexp1 }}'
    replace: '{{ item.replace }}'
  with_items:
    - { regexp1: 'WEBHOOK_URL', replace: '{{ webhook_url }}' }
    - { regexp1: 'PROM_ENDPOINT', replace: '{{ prom_endpoint }}' }
    - { regexp1: 'SLACK_CHANNEL', replace: '{{ channel }}' }
  notify: event_restart_alertmanager

- name: Copy systemd init file
  template:
    src: init.service.j2
    dest: /etc/systemd/system/alertmanager.service
  notify: systemd_reload

- name: Start alertmanager service
  service:
    name: alertmanager
    state: restarted
    enabled: yes

- name: Check if alertmanager is accessible
  uri:
    url: http://localhost:9093
    method: GET
    status_code: 200